from .base import db
from .usuario import Usuario
from .academia import Academia
from .atleta import Atleta
from .categoria import Categoria
from .competicao import Competicao
from .inscricao import Inscricao
from .luta import Luta
from .resultado import Resultado
from .pagamento import Pagamento
